# Generated by Django 4.0.5 on 2022-07-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Rolno', models.CharField(max_length=30)),
                ('dep', models.CharField(max_length=30)),
                ('mark1', models.IntegerField(max_length=10)),
                ('mark2', models.IntegerField(max_length=10)),
                ('mark3', models.IntegerField(max_length=10)),
                ('mark4', models.IntegerField(max_length=10)),
            ],
        ),
    ]
