# Generated by Django 4.0.5 on 2022-07-05 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='mark1',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='mark2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='mark3',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='mark4',
        ),
    ]
