# Generated by Django 4.0.5 on 2022-07-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_mark1_remove_blog_mark2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='mark1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='mark2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='mark3',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='mark4',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
