# Generated by Django 4.0.5 on 2022-07-06 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_mark1_blog_mark2_blog_mark3_blog_mark4'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blog',
            table='stud',
        ),
    ]
